url: https://smartloan.github.io
baseurl: /smartloan-page/

# Site settings
title: SmartLoan
email: asvoria@live.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Asvoria Kuan
  pic: 1
  position: Lead Researcher & Developer
  social:
    - title: youtube
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Ian Munge
  pic: 2
  position: dApp Developer
  social:
    - title: github
      url: #

- name: Eddy Kuan
  pic: 3
  position: dApp Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-cayman
